CREATE TABLE cars(id INT auto_increment PRIMARY KEY, make VARCHAR(50), model VARCHAR(50), category VARCHAR(20), price float, fabyear INT, km float, cc float, fuel VARCHAR(20), power int, gearbox VARCHAR(20), transmission VARCHAR(20), polution VARCHAR(20))

INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('1', 'Audi', 'A5', 'sedan', '20000', '2019', '84255', '2968', 'diesel', '286', 'auto', '4x4', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('2', 'Ford', 'Edge', 'suv', '18000', '2016', '58000', '2968', 'diesel', '320', 'auto', '4x4', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('3', 'Volkswagen', 'Passat', 'sedan', '14000', '2017', '136000', '1968', 'diesel', '190', 'auto', '4x4', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('4', 'Renault', 'Twingo', 'hatchback', '7000', '2018', '7000', '999', 'gas', '70', 'manual', 'fwd', 'euro5');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('5', 'Opel', 'Insignia', 'sedan', '10000', '2016', '129000', '1968', 'diesel', '170', 'auto', 'fwd', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('6', 'Volkswagen', 'Golf', 'hatchback', '8000', '2016', '174000', '2000', 'gas', '150', 'auto', 'fwd', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('7', 'BMW', '118', 'hatchback', '9500', '2016', '175000', '1998', 'diesel', '136', 'auto', 'rwd', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('8', 'Mercedes-Benz', 'A180', 'hatchback', '8500', '2014', '177954', '1461', 'diesel', '109', 'manual', 'fwd', 'euro5');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('9', 'Seat', 'Leon FR', 'hatchback', '13000', '2019', '20234', '1461', 'gas', '130', 'auto', 'fwd', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('10', 'Kia', 'Pro cee\'d', 'hatchback', '5500', '2008', '131790', '2000', 'gas', '140', 'manual', 'fwd', 'euro5');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('11', 'Porsche', 'Boxster', 'convertible', '3500', '1998', '193315', '2480', 'gas', '204', 'auto', 'rwd', 'euro4');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('12', 'Jaguar', 'XK', 'convertible', '18000', '2011', '80000', '2995', 'gas', '300', 'auto', 'fwd', 'euro5');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('13', 'Range Rover', 'Evoque', 'suv', '17500', '2016', '99000', '1998', 'diesel', '180', 'auto', '4x4', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('14', 'Volvo', 'S60', 'sedan', '12000', '2015', '192200', '1969', 'diesel', '120', 'auto', 'fwd', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('15', 'Toyota', 'GT86', 'coupe', '11000', '2012', '91940', '1998', 'gas', '200', 'manual', 'rwd', 'euro5');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('16', 'Fiat', '500 Abarth', 'hatchback', '9000', '2009', '139000', '1368', 'gas', '135', 'manual', 'fwd', 'euro5');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('17', 'Hyundai', 'i30', 'sedan', '12000', '2018', '25000', '1353', 'gas', '140', 'auto', 'fwd', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('18', 'Chevrolet', 'Camaro SS', 'sports', '28000', '2017', '29500', '2500', 'gas', '275', 'auto', 'rwd', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('19', 'Mitsubishi', 'Outlander', 'suv', '30000', '2019', '10', '2360', 'hybrid', '135', 'auto', '4x4', 'euro6');
INSERT INTO `siteril`.`cars` (`id`, `make`, `model`, `category`, `price`, `fabyear`, `km`, `cc`, `fuel`, `power`, `gearbox`, `transmission`, `polution`) VALUES ('20', 'Mazda', '3', 'hatchback', '17500', '2017', '33700', '1499', 'diesel', '105', 'manual', 'fwd', 'euro6');